### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [kofinkansah/firehose_work#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by kofinkansah** [comment]
Ahh, thanks Ken. I added the a viewport line of code to my application and it looks much better. Only thing is it doesn't seem to randomize anymore online. It seems to be stuck on Splurty No.1. Do you know why? It still works just as well as before on my local environment.

**Comment by kenmazaika** [comment]
Cool!  Glad you got it.  I think if you watch the next video overview lessons they'll go over the reason.  In short, there's two different databases.  One on heroku and one on localhost.  If you add new quotes to heroku it should cycle through them.  Keep up the good work coding! :)

**Comment by kofinkansah** [comment]
Ohh! You're right. I only had one quote added to my heroku database up to
that point. Thanks Ken!

**Comment by kenmazaika** [comment]
Happy to help! :)
